# Constants for environment variables
OPENAI_API_KEY = "OPENAI_API_KEY"
TO_EMAIL = "TO_EMAIL"
NAME = "NAME"
EMAIL_ADDRESS = "EMAIL_ADDRESS"
EMAIL_PASSWORD = "EMAIL_PASSWORD"
SMTP_SERVER = "SMTP_SERVER"
SMTP_PORT = "SMTP_PORT"
